# Generated by Django 5.0.7 on 2024-07-30 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_expense_split_method_alter_expense_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='split_method',
            field=models.CharField(choices=[('equal', 'Equal'), ('exact', 'Exact'), ('percentage', 'Percentage')], default='equal', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_expense', to=settings.AUTH_USER_MODEL),
        ),
    ]
