# Generated by Django 5.0.7 on 2024-07-30 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_balancesheet_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BalanceSheet',
        ),
    ]
