# Generated by Django 5.0.7 on 2024-07-30 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_expense_split_method_alter_expense_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensesplit',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='expensesplit',
            name='user',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='ExpenseSplit',
        ),
    ]
