# Generated by Django 5.0.7 on 2024-07-30 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_balancesheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancesheet',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='expense_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.expense'),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_balance_sheets', to=settings.AUTH_USER_MODEL),
        ),
    ]
